### ISSUE TITLE
Script hangs on thorough search if host is down

### ISSUE THREAD

**Issue by hannestrunde** [fireeye/SessionGopher#1]
First of all: very cool tool you've created here!

I ran across an issue when invoking SessionGopher on a list of hosts where some of them are not online.
If I run the following command, everything works fine and SessionGopher ignores the hosts not online:
```
Invoke-SessionGopher -iL .\computerlist.txt -o
[+] Digging on srv01...
Invoke-WmiMethod : Anbieter wurde nicht gefunden.
In Zeile:115 Zeichen:15
+ ...     $SIDS = Invoke-WmiMethod -Class 'StdRegProv' -Name 'EnumKey' -Arg ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-WmiMethod], ManagementException
    + FullyQualifiedErrorId : InvokeWMIManagementException,Microsoft.PowerShell.Commands.InvokeWmiMethod

[+] Digging on srv02...
[+] Digging on srv03...
```

If I run the same command with the -Thorough flag, SessionsGopher seems to hang indefinitely on the first host which is not online:
```
Invoke-SessionGopher -iL .\computerlist.txt -Thorough -o
[+] Digging on srv01...
Invoke-WmiMethod : Anbieter wurde nicht gefunden.
In Zeile:115 Zeichen:15
+ ...     $SIDS = Invoke-WmiMethod -Class 'StdRegProv' -Name 'EnumKey' -Arg ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-WmiMethod], ManagementException
    + FullyQualifiedErrorId : InvokeWMIManagementException,Microsoft.PowerShell.Commands.InvokeWmiMethod
```

**Comment by Arvanaghi** [comment]
Thank you Hannes for pointing this out. I will look into it!

**Comment by Arvanaghi** [comment]
Hi Hannes,

I'm not able to reproduce this problem on my end. It looks like SessionGopher continues with the next host even when using `-Thorough` and the host is down. I get two error messages and then it proceeds. 

Can you double check this on your end?

Thanks,

Brandon
